//
//  Emoji.swift
//  Chameleon
//
//  Created by Ian Keen on 6/06/2016.
//
//

/// An abstraction for an object that can represent an emoji 
public protocol SlackEmoji: JSONRepresentable {
    /// The string slack uses to identify this emoji
    var emojiSymbol: String { get }
}
extension SlackEmoji {
    public func makeJSON() -> JSON {
        return JSON.string(self.emojiSymbol)
    }
}

//From: https://github.com/iamcal/emoji-data
public enum Emoji: String, JSONRepresentable {
    case hash
    case zero
    case one
    case two
    case three
    case four
    case five
    case six
    case seven
    case eight
    case nine
    case copyright
    case registered
    case mahjong
    case black_joker
    case a
    case b
    case o2
    case parking
    case ab
    case cl
    case cool
    case free
    case id
    case new
    case ng
    case ok
    case sos
    case up
    case vs
    case cn
    case de
    case es
    case fr
    case gb
    case uk
    case it
    case jp
    case kr
    case ru
    case us
    case koko
    case sa
    case u7121
    case u6307
    case u7981
    case u7a7a
    case u5408
    case u6e80
    case u6709
    case u6708
    case u7533
    case u5272
    case u55b6
    case ideograph_advantage
    case accept
    case cyclone
    case foggy
    case closed_umbrella
    case night_with_stars
    case sunrise_over_mountains
    case sunrise
    case city_sunset
    case city_sunrise
    case rainbow
    case bridge_at_night
    case ocean
    case volcano
    case milky_way
    case earth_africa
    case earth_americas
    case earth_asia
    case globe_with_meridians
    case new_moon
    case waxing_crescent_moon
    case first_quarter_moon
    case moon
    case waxing_gibbous_moon
    case full_moon
    case waning_gibbous_moon
    case last_quarter_moon
    case waning_crescent_moon
    case crescent_moon
    case new_moon_with_face
    case first_quarter_moon_with_face
    case last_quarter_moon_with_face
    case full_moon_with_face
    case sun_with_face
    case star2
    case stars
    case chestnut
    case seedling
    case evergreen_tree
    case deciduous_tree
    case palm_tree
    case cactus
    case tulip
    case cherry_blossom
    case rose
    case hibiscus
    case sunflower
    case blossom
    case corn
    case ear_of_rice
    case herb
    case four_leaf_clover
    case maple_leaf
    case fallen_leaf
    case leaves
    case mushroom
    case tomato
    case eggplant
    case grapes
    case melon
    case watermelon
    case tangerine
    case lemon
    case banana
    case pineapple
    case apple
    case green_apple
    case pear
    case peach
    case cherries
    case strawberry
    case hamburger
    case pizza
    case meat_on_bone
    case poultry_leg
    case rice_cracker
    case rice_ball
    case rice
    case curry
    case ramen
    case spaghetti
    case bread
    case fries
    case sweet_potato
    case dango
    case oden
    case sushi
    case fried_shrimp
    case fish_cake
    case icecream
    case shaved_ice
    case ice_cream
    case doughnut
    case cookie
    case chocolate_bar
    case candy
    case lollipop
    case custard
    case honey_pot
    case cake
    case bento
    case stew
    case egg
    case fork_and_knife
    case tea
    case sake
    case wine_glass
    case cocktail
    case tropical_drink
    case beer
    case beers
    case baby_bottle
    case ribbon
    case gift
    case birthday
    case jack_o_lantern
    case christmas_tree
    case santa
    case fireworks
    case sparkler
    case balloon
    case tada
    case confetti_ball
    case tanabata_tree
    case crossed_flags
    case bamboo
    case dolls
    case flags
    case wind_chime
    case rice_scene
    case school_satchel
    case mortar_board
    case carousel_horse
    case ferris_wheel
    case roller_coaster
    case fishing_pole_and_fish
    case microphone
    case movie_camera
    case cinema
    case headphones
    case art
    case tophat
    case circus_tent
    case ticket
    case clapper
    case performing_arts
    case video_game
    case dart
    case slot_machine
    case eightBall = "8ball"
    case game_die
    case bowling
    case flower_playing_cards
    case musical_note
    case notes
    case saxophone
    case guitar
    case musical_keyboard
    case trumpet
    case violin
    case musical_score
    case running_shirt_with_sash
    case tennis
    case ski
    case basketball
    case checkered_flag
    case snowboarder
    case runner
    case running
    case surfer
    case trophy
    case horse_racing
    case football
    case rugby_football
    case swimmer
    case house
    case house_with_garden
    case office
    case post_office
    case european_post_office
    case hospital
    case bank
    case atm
    case hotel
    case love_hotel
    case convenience_store
    case school
    case department_store
    case factory
    case izakaya_lantern
    case lantern
    case japanese_castle
    case european_castle
    case rat
    case mouse2
    case ox
    case water_buffalo
    case cow2
    case tiger2
    case leopard
    case rabbit2
    case cat2
    case dragon
    case crocodile
    case whale2
    case snail
    case snake
    case racehorse
    case ram
    case goat
    case sheep
    case monkey
    case rooster
    case chicken
    case dog2
    case pig2
    case boar
    case elephant
    case octopus
    case shell
    case bug
    case ant
    case bee
    case honeybee
    case beetle
    case fish
    case tropical_fish
    case blowfish
    case turtle
    case hatching_chick
    case baby_chick
    case hatched_chick
    case bird
    case penguin
    case koala
    case poodle
    case dromedary_camel
    case camel
    case dolphin
    case flipper
    case mouse
    case cow
    case tiger
    case rabbit
    case cat
    case dragon_face
    case whale
    case horse
    case monkey_face
    case dog
    case pig
    case frog
    case hamster
    case wolf
    case bear
    case panda_face
    case pig_nose
    case feet
    case paw_prints
    case eyes
    case ear
    case nose
    case lips
    case tongue
    case point_up_2
    case point_down
    case point_left
    case point_right
    case facepunch
    case punch
    case wave
    case ok_hand
    case plus1 = "+1"
    case thumbsup
    case minus1 = "-1"
    case thumbsdown
    case clap
    case open_hands
    case crown
    case womans_hat
    case eyeglasses
    case necktie
    case shirt
    case tshirt
    case jeans
    case dress
    case kimono
    case bikini
    case womans_clothes
    case purse
    case handbag
    case pouch
    case mans_shoe
    case shoe
    case athletic_shoe
    case high_heel
    case sandal
    case boot
    case footprints
    case bust_in_silhouette
    case busts_in_silhouette
    case boy
    case girl
    case man
    case woman
    case family
    case man_woman_boy = "man-woman-boy"
    case couple
    case man_and_woman_holding_hands
    case two_men_holding_hands
    case two_women_holding_hands
    case cop
    case dancers
    case bride_with_veil
    case person_with_blond_hair
    case man_with_gua_pi_mao
    case man_with_turban
    case older_man
    case older_woman
    case baby
    case construction_worker
    case princess
    case japanese_ogre
    case japanese_goblin
    case ghost
    case angel
    case alien
    case space_invader
    case imp
    case skull
    case information_desk_person
    case guardsman
    case dancer
    case lipstick
    case nail_care
    case massage
    case haircut
    case barber
    case syringe
    case pill
    case kiss
    case love_letter
    case ring
    case gem
    case couplekiss
    case bouquet
    case couple_with_heart
    case wedding
    case heartbeat
    case broken_heart
    case two_hearts
    case sparkling_heart
    case heartpulse
    case cupid
    case blue_heart
    case green_heart
    case yellow_heart
    case purple_heart
    case gift_heart
    case revolving_hearts
    case heart_decoration
    case diamond_shape_with_a_dot_inside
    case bulb
    case anger
    case bomb
    case zzz
    case boom
    case collision
    case sweat_drops
    case droplet
    case dash
    case hankey
    case poop
    case shit
    case muscle
    case dizzy
    case speech_balloon
    case thought_balloon
    case white_flower
    case oneHundred = "100"
    case moneybag
    case currency_exchange
    case heavy_dollar_sign
    case credit_card
    case yen
    case dollar
    case euro
    case pound
    case money_with_wings
    case chart
    case seat
    case computer
    case briefcase
    case minidisc
    case floppy_disk
    case cd
    case dvd
    case file_folder
    case open_file_folder
    case page_with_curl
    case page_facing_up
    case date
    case calendar
    case card_index
    case chart_with_upwards_trend
    case chart_with_downwards_trend
    case bar_chart
    case clipboard
    case pushpin
    case round_pushpin
    case paperclip
    case straight_ruler
    case triangular_ruler
    case bookmark_tabs
    case ledger
    case notebook
    case notebook_with_decorative_cover
    case closed_book
    case book
    case open_book
    case green_book
    case blue_book
    case orange_book
    case books
    case name_badge
    case scroll
    case memo
    case pencil
    case telephone_receiver
    case pager
    case fax
    case satellite_antenna
    case loudspeaker
    case mega
    case outbox_tray
    case inbox_tray
    case package
    case e_mail = "e-mail"
    case incoming_envelope
    case envelope_with_arrow
    case mailbox_closed
    case mailbox
    case mailbox_with_mail
    case mailbox_with_no_mail
    case postbox
    case postal_horn
    case newspaper
    case iphone
    case calling
    case vibration_mode
    case mobile_phone_off
    case no_mobile_phones
    case signal_strength
    case camera
    case video_camera
    case tv
    case radio
    case vhs
    case twisted_rightwards_arrows
    case `repeat`
    case repeat_one
    case arrows_clockwise
    case arrows_counterclockwise
    case low_brightness
    case high_brightness
    case mute
    case speaker
    case sound
    case loud_sound
    case battery
    case electric_plug
    case mag
    case mag_right
    case lock_with_ink_pen
    case closed_lock_with_key
    case key
    case lock
    case unlock
    case bell
    case no_bell
    case bookmark
    case link
    case radio_button
    case back
    case end
    case on
    case soon
    case top
    case underage
    case keycap_ten
    case capital_abcd
    case abcd
    case oneTwoThreeFour = "1234"
    case symbols
    case abc
    case fire
    case flashlight
    case wrench
    case hammer
    case nut_and_bolt
    case hocho
    case knife
    case gun
    case microscope
    case telescope
    case crystal_ball
    case six_pointed_star
    case beginner
    case trident
    case black_square_button
    case white_square_button
    case red_circle
    case large_blue_circle
    case large_orange_diamond
    case large_blue_diamond
    case small_orange_diamond
    case small_blue_diamond
    case small_red_triangle
    case small_red_triangle_down
    case arrow_up_small
    case arrow_down_small
    case clock1
    case clock2
    case clock3
    case clock4
    case clock5
    case clock6
    case clock7
    case clock8
    case clock9
    case clock10
    case clock11
    case clock12
    case clock130
    case clock230
    case clock330
    case clock430
    case clock530
    case clock630
    case clock730
    case clock830
    case clock930
    case clock1030
    case clock1130
    case clock1230
    case mount_fuji
    case tokyo_tower
    case statue_of_liberty
    case japan
    case moyai
    case grinning
    case grin
    case joy
    case smiley
    case smile
    case sweat_smile
    case laughing
    case satisfied
    case innocent
    case smiling_imp
    case wink
    case blush
    case yum
    case relieved
    case heart_eyes
    case sunglasses
    case smirk
    case neutral_face
    case expressionless
    case unamused
    case sweat
    case pensive
    case confused
    case confounded
    case kissing
    case kissing_heart
    case kissing_smiling_eyes
    case kissing_closed_eyes
    case stuck_out_tongue
    case stuck_out_tongue_winking_eye
    case stuck_out_tongue_closed_eyes
    case disappointed
    case worried
    case angry
    case rage
    case cry
    case persevere
    case triumph
    case disappointed_relieved
    case frowning
    case anguished
    case fearful
    case weary
    case sleepy
    case tired_face
    case grimacing
    case sob
    case open_mouth
    case hushed
    case cold_sweat
    case scream
    case astonished
    case flushed
    case sleeping
    case dizzy_face
    case no_mouth
    case mask
    case smile_cat
    case joy_cat
    case smiley_cat
    case heart_eyes_cat
    case smirk_cat
    case kissing_cat
    case pouting_cat
    case crying_cat_face
    case scream_cat
    case no_good
    case ok_woman
    case bow
    case see_no_evil
    case hear_no_evil
    case speak_no_evil
    case raising_hand
    case raised_hands
    case person_frowning
    case person_with_pouting_face
    case pray
    case rocket
    case helicopter
    case steam_locomotive
    case railway_car
    case bullettrain_side
    case bullettrain_front
    case train2
    case metro
    case light_rail
    case station
    case tram
    case train
    case bus
    case oncoming_bus
    case trolleybus
    case busstop
    case minibus
    case ambulance
    case fire_engine
    case police_car
    case oncoming_police_car
    case taxi
    case oncoming_taxi
    case car
    case red_car
    case oncoming_automobile
    case blue_car
    case truck
    case articulated_lorry
    case tractor
    case monorail
    case mountain_railway
    case suspension_railway
    case mountain_cableway
    case aerial_tramway
    case ship
    case rowboat
    case speedboat
    case traffic_light
    case vertical_traffic_light
    case construction
    case rotating_light
    case triangular_flag_on_post
    case door
    case no_entry_sign
    case smoking
    case no_smoking
    case put_litter_in_its_place
    case do_not_litter
    case potable_water
    case non_potable_water = "non-potable_water"
    case bike
    case no_bicycles
    case bicyclist
    case mountain_bicyclist
    case walking
    case no_pedestrians
    case children_crossing
    case mens
    case womens
    case restroom
    case baby_symbol
    case toilet
    case wc
    case shower
    case bath
    case bathtub
    case passport_control
    case customs
    case baggage_claim
    case left_luggage
    case bangbang
    case leftwards_arrow_with_hook
    case arrow_right_hook
    case watch
    case hourglass
    case rewind
    case arrow_double_up
    case arrow_double_down
    case alarm_clock
    case hourglass_flowing_sand
    case m
    case black_small_square
    case white_small_square
    case arrow_forward
    case arrow_backward
    case white_medium_square
    case black_medium_square
    case white_medium_small_square
    case black_medium_small_square
    case phone
    case telephone
    case point_up
    case relaxed
    case gemini
    case cancer
    case leo
    case virgo
    case libra
    case scorpius
    case recycle
    case wheelchair
    case warning
    case zap
    case white_circle
    case black_circle
    case soccer
    case baseball
    case snowman_without_snow
    case partly_sunny
    case ophiuchus
    case no_entry
    case church
    case fountain
    case golf
    case boat
    case sailboat
    case tent
    case fuelpump
    case fist
    case hand
    case raised_hand
    case v
    case pencil2
    case x
    case negative_squared_cross_mark
    case arrow_right
    case curly_loop
    case loop
    case arrow_left
    case arrow_up
    case arrow_down
    case black_large_square
    case white_large_square
    case star
    case o
    case part_alternation_mark
    case interrobang
    case tm
    case information_source
    case left_right_arrow
    case arrow_up_down
    case arrow_upper_left
    case arrow_upper_right
    case arrow_lower_right
    case arrow_lower_left
    case sunny
    case cloud
    case ballot_box_with_check
    case umbrella_with_rain_drops
    case coffee
    case aries
    case taurus
    case sagittarius
    case capricorn
    case aquarius
    case pisces
    case spades
    case clubs
    case hearts
    case diamonds
    case hotsprings
    case anchor
    case scissors
    case white_check_mark
    case airplane
    case email
    case envelope
    case black_nib
    case heavy_check_mark
    case heavy_multiplication_x
    case sparkles
    case eight_spoked_asterisk
    case eight_pointed_black_star
    case snowflake
    case sparkle
    case question
    case grey_question
    case grey_exclamation
    case exclamation
    case heavy_exclamation_mark
    case heart
    case heavy_plus_sign
    case heavy_minus_sign
    case heavy_division_sign
    case arrow_heading_up
    case arrow_heading_down
    case wavy_dash
    case congratulations
    case secret
    case fast_forward
}
